# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y1jRJvzhlUjdd66vnUOBj57YzwXHYc1s
"""

# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y1jRJvzhlUjdd66vnUOBj57YzwXHYc1s
"""

# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y1jRJvzhlUjdd66vnUOBj57YzwXHYc1s
"""

# -*- coding: utf-8 -*-
"""
台灣 ETF 個人化推薦系統 - 參數敏感度修正版
修正問題：
1. 風險厭惡係數範圍調整為實證區間 [1, 4]
2. 採用對數效用函數提升敏感度
3. 配息偏好獨立建模
4. 新增 Certainty Equivalent Return (CER)
5. 時間範圍影響折現率

理論依據：
- Mehra & Prescott (1985): Equity Premium Puzzle
- Campbell & Viceira (2002): Strategic Asset Allocation
- Cochrane (2005): Asset Pricing
"""

import streamlit as st
import pandas as pd
import numpy as np
import yfinance as yf
from datetime import datetime, timedelta
from scipy import stats
from scipy.optimize import minimize_scalar
import plotly.graph_objects as go
import plotly.express as px
import altair as alt
import requests
import warnings
from typing import Dict, Tuple, Optional, List
from dataclasses import dataclass
import logging

warnings.filterwarnings('ignore')
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# ===============================
# 學術常數（基於實證研究）
# ===============================
TRADING_DAYS = 252
RISK_FREE_RATE = 0.015  # 台灣10年期公債
MARKET_RISK_PREMIUM = 0.065  # 台股歷史風險溢價

# ETF定義（預設備援）
DEFAULT_ETF_LIST = {
    "0050.TW": "股票型",
    "006208.TW": "股票型", 
    "00692.TW": "股票型",
    "00757.TW": "股票型",
    "0056.TW": "高股息型",
    "00878.TW": "高股息型",
    "00919.TW": "高股息型",
}
MARKET_BENCHMARK = "0050.TW"


def _classify_etf_type(etf_name: str) -> str:
    """根據ETF名稱進行簡單分類。"""
    if not etf_name:
        return "ETF"
    if "高股息" in etf_name:
        return "高股息型"
    if "債" in etf_name:
        return "債券型"
    if "反1" in etf_name:
        return "反向型"
    if "正2" in etf_name:
        return "槓桿型"
    if "REIT" in etf_name.upper() or "不動產" in etf_name:
        return "不動產型"
    return "股票型"


@st.cache_data(ttl=60 * 60 * 12)
def _fetch_all_tw_etf() -> Dict[str, str]:
    """抓取台灣上市櫃ETF代碼，失敗時回退預設備援清單。"""
    etf_map: Dict[str, str] = {}
    headers = {"User-Agent": "Mozilla/5.0"}
    sources = [
        ("TWSE", "https://openapi.twse.com.tw/v1/exchangeReport/STOCK_DAY_ALL", ".TW"),
        ("TPEx", "https://www.tpex.org.tw/openapi/v1/tpex_esb_capitals_rank", ".TWO"),
    ]

    for source_name, url, suffix in sources:
        source_count = 0
        try:
            response = requests.get(url, timeout=12, headers=headers)
            response.raise_for_status()
            payload = response.json()
            if not isinstance(payload, list):
                continue

            for item in payload:
                raw_code = str(
                    item.get("Code")
                    or item.get("SecuritiesCompanyCode")
                    or item.get("股票代號")
                    or ""
                ).strip()
                name = str(
                    item.get("Name")
                    or item.get("CompanyName")
                    or item.get("股票名稱")
                    or ""
                ).strip()

                if raw_code.isdigit() and len(raw_code) == 4 and raw_code.startswith("00"):
                    etf_map[f"{raw_code}{suffix}"] = _classify_etf_type(name)
                    source_count += 1

            logger.info("%s ETF 清單筆數: %d", source_name, source_count)
        except Exception as e:
            logger.warning("%s ETF 清單抓取失敗: %s", source_name, e)

    if not etf_map:
        logger.warning("ETF 清單抓取失敗，改用預設清單")
        return DEFAULT_ETF_LIST.copy()

    if MARKET_BENCHMARK not in etf_map:
        etf_map[MARKET_BENCHMARK] = DEFAULT_ETF_LIST.get(MARKET_BENCHMARK, "股票型")

    return dict(sorted(etf_map.items()))


ETF_LIST = _fetch_all_tw_etf()

# ===============================
# 資料結構
# ===============================
@dataclass
class FinancialMetrics:
    """財務指標"""
    ann_return: float
    ann_volatility: float
    sharpe_ratio: float
    sortino_ratio: float
    beta: float
    alpha: float
    max_drawdown: float
    
    # 標準誤
    return_se: float
    volatility_se: float
    beta_se: float
    sharpe_pvalue: float

@dataclass
class RiskProfile:
    """風險偏好檔案"""
    theta: float  # 風險容忍度 [0,1]
    risk_aversion: float  # γ ∈ [1,4]
    time_horizon: float  # 年數
    income_stability: float  # [0,1]
    loss_tolerance: float  # [0,1]
    dividend_preference: float  # [0,1]
    profile_confidence: float = 0.0  # 問卷品質信心 [0,1]


class QuestionnaireCritic:
    """在不改UI前提下，量化問卷訊號是否足以支持強結論。"""

    MIN_ITEMS_FOR_STABLE_INFERENCE = 12  # 行為金融問卷常見最低題數

    @staticmethod
    def estimate_confidence(
        responses: Dict[str, float],
        weights: Dict[str, float],
        option_count: int = 5,
    ) -> float:
        """估計量表信心分數，題目越少、維度越集中，信心越低。"""
        n_items = len(responses)
        item_adequacy = np.clip(n_items / QuestionnaireCritic.MIN_ITEMS_FOR_STABLE_INFERENCE, 0, 1)

        # 權重集中度：若過度依賴少數題目，推論容易失真
        weight_values = np.array(list(weights.values()), dtype=float)
        concentration = float(np.sum(weight_values ** 2))
        diversification = 1 - np.clip((concentration - 1 / len(weight_values)) / (1 - 1 / len(weight_values)), 0, 1)

        # 離散選項解析度（5點量表只能粗略切分心理特質）
        resolution = np.clip((option_count - 1) / 9, 0, 1)  # 10點量表視為較理想

        # 回答內在一致性：極端矛盾時降低信心
        response_values = np.array(list(responses.values()), dtype=float)
        coherence = 1 - np.clip(np.std(response_values) / 0.5, 0, 1)

        confidence = 0.45 * item_adequacy + 0.25 * diversification + 0.15 * resolution + 0.15 * coherence
        return float(np.clip(confidence, 0.05, 0.95))

@dataclass  
class DividendInfo:
    """配息資訊"""
    latest_date: Optional[datetime]
    latest_amount: float
    ttm_dividend: float
    ttm_yield: float
    data_source: str

# ===============================
# UI設定
# ===============================
st.set_page_config(page_title="台灣 ETF 個人化推薦系統", layout="wide")
st.title("📊 台灣 ETF 個人化推薦系統（參數敏感度修正版）")
st.caption("⚠️ 基於實證風險偏好理論，確保不同投資人看到明顯差異的推薦結果")

# ===============================
# Sidebar: 風險偏好評估
# ===============================
st.sidebar.header("👤 投資人風險偏好評估")
st.sidebar.markdown("**實證驗證問卷**")

# Q1: Investment Horizon
st.sidebar.markdown("---")
st.sidebar.subheader("Q1. 投資時間範圍")
horizon_mapping = {
    "少於 1 年": (0.5, 0.0, 1.20),     # (年數, 分數, 折現係數)
    "1-3 年": (2, 0.20, 1.10),
    "4-6 年": (5, 0.40, 1.05),
    "7-10 年": (8.5, 0.65, 1.02),
    "10 年以上": (15, 1.0, 1.00)
}
horizon_choice = st.sidebar.radio(
    "選擇投資期間",
    list(horizon_mapping.keys()),
    index=3,
    help="長期投資人可承受更高波動"
)
horizon_years, horizon_score, discount_factor = horizon_mapping[horizon_choice]

# Q2: Risk Capacity
st.sidebar.markdown("---")
st.sidebar.subheader("Q2. 如果您有一筆閒置資金，您會選擇？")
risk_capacity_mapping = {
    "存入銀行或購買政府公債（幾乎無風險）": 0.0,
    "購買債券型基金（低風險，報酬穩定）": 0.25,
    "購買混合型基金（中等風險與報酬）": 0.50,
    "購買股票型基金（高風險，追求高報酬）": 0.75,
    "購買個股或高風險商品（承受重大虧損風險）": 1.0
}
risk_capacity = st.sidebar.radio(
    "投資偏好",
    list(risk_capacity_mapping.keys()),
    index=2
)
capacity_score = risk_capacity_mapping[risk_capacity]

# Q3: Loss Tolerance (關鍵問題)
st.sidebar.markdown("---")
st.sidebar.subheader("Q3. 損失容忍度")
loss_tolerance_mapping = {
    "立即全部賣出": 0.0,
    "賣出一半": 0.20,
    "維持不動": 0.50,
    "小幅加碼": 0.80,
    "大幅加碼": 1.0
}
loss_tolerance = st.sidebar.radio(
    "若投資組合一個月內下跌20%，您會？",
    list(loss_tolerance_mapping.keys()),
    index=2,
    help="最能區分保守/積極型投資人的問題"
)
loss_score = loss_tolerance_mapping[loss_tolerance]

# Q4: Income Stability
st.sidebar.markdown("---")
st.sidebar.subheader("Q4. 收入穩定性")
income_stability_mapping = {
    "非常不穩定": 0.0,
    "不穩定": 0.25,
    "普通": 0.50,
    "穩定": 0.75,
    "非常穩定": 1.0
}
income_stability = st.sidebar.selectbox(
    "收入狀況",
    list(income_stability_mapping.keys()),
    index=2
)
income_score = income_stability_mapping[income_stability]

# Q5: Dividend Preference (新增)
st.sidebar.markdown("---")
st.sidebar.subheader("Q5. 配息偏好")
dividend_pref_mapping = {
    "完全不在乎配息，追求總報酬": 0.0,
    "配息次要，報酬優先": 0.25,
    "配息與報酬同等重要": 0.50,
    "配息優先，可接受較低報酬": 0.75,
    "只要穩定配息，報酬其次": 1.0
}
dividend_pref = st.sidebar.radio(
    "配息重要性",
    list(dividend_pref_mapping.keys()),
    index=2,
    help="高股息ETF vs 成長型ETF的偏好"
)
dividend_pref_score = dividend_pref_mapping[dividend_pref]

# Q6: Age
st.sidebar.markdown("---")
st.sidebar.subheader("Q6. 年齡")
age = st.sidebar.slider("年齡", 20, 80, 35)
age_score = max(0, min(1, (80 - age) / 60))  # 修正：年輕人更能承受風險

# ===============================
# θ 計算（實證權重 + 新增配息偏好）
# ===============================
st.sidebar.markdown("---")
st.sidebar.subheader("📊 風險偏好計算")

# 實證權重（來源：Grable 2008）
EMPIRICAL_WEIGHTS = {
    'capacity': 0.30,     # 風險承受能力
    'loss': 0.30,         # 損失容忍度（最關鍵）
    'horizon': 0.20,      # 投資期間
    'income': 0.10,       # 收入穩定性
    'age': 0.10          # 年齡
}

theta = (
    EMPIRICAL_WEIGHTS['capacity'] * capacity_score +
    EMPIRICAL_WEIGHTS['loss'] * loss_score +
    EMPIRICAL_WEIGHTS['horizon'] * horizon_score +
    EMPIRICAL_WEIGHTS['income'] * income_score +
    EMPIRICAL_WEIGHTS['age'] * age_score
)

theta = np.clip(theta, 0, 1)

response_vector = {
    "horizon": horizon_score,
    "capacity": capacity_score,
    "loss": loss_score,
    "income": income_score,
    "age": age_score,
    "dividend": dividend_pref_score,
}
profile_confidence = QuestionnaireCritic.estimate_confidence(
    response_vector,
    {
        "capacity": EMPIRICAL_WEIGHTS['capacity'],
        "loss": EMPIRICAL_WEIGHTS['loss'],
        "horizon": EMPIRICAL_WEIGHTS['horizon'],
        "income": EMPIRICAL_WEIGHTS['income'],
        "age": EMPIRICAL_WEIGHTS['age'],
        "dividend": 0.20,
    },
)

# 風險厭惡係數（修正範圍）
# 實證研究：Chetty (2006) γ ∈ [1, 5]，中位數 ≈ 2
# Mehra & Prescott (1985): γ ≈ 1-4 才能解釋股權溢價
risk_aversion_min = 1.0  # 極度積極
risk_aversion_max = 4.0  # 極度保守
risk_aversion = risk_aversion_max - (risk_aversion_max - risk_aversion_min) * theta

st.sidebar.metric("θ (風險偏好指數)", f"{theta:.3f}")
st.sidebar.metric("γ (風險厭惡係數)", f"{risk_aversion:.2f}")
st.sidebar.metric("配息偏好", f"{dividend_pref_score:.2f}")
st.sidebar.metric("問卷信心", f"{profile_confidence:.2f}")

risk_profile_label = (
    "🔵 極度保守" if theta < 0.2 else
    "🟢 保守" if theta < 0.4 else
    "🟡 穩健" if theta < 0.6 else
    "🟠 積極" if theta < 0.8 else
    "🔴 非常積極"
)
st.sidebar.info(f"**風險類型**：{risk_profile_label}")

# 創建風險檔案
risk_profile = RiskProfile(
    theta=theta,
    risk_aversion=risk_aversion,
    time_horizon=horizon_years,
    income_stability=income_score,
    loss_tolerance=loss_score,
    dividend_preference=dividend_pref_score,
    profile_confidence=profile_confidence
)

with st.sidebar.expander("📋 評分明細"):
    st.write(f"**θ 計算：**")
    st.write(f"- 風險承受：{capacity_score:.2f} × {EMPIRICAL_WEIGHTS['capacity']:.0%} = {capacity_score * EMPIRICAL_WEIGHTS['capacity']:.3f}")
    st.write(f"- 損失容忍：{loss_score:.2f} × {EMPIRICAL_WEIGHTS['loss']:.0%} = {loss_score * EMPIRICAL_WEIGHTS['loss']:.3f}")
    st.write(f"- 投資期間：{horizon_score:.2f} × {EMPIRICAL_WEIGHTS['horizon']:.0%} = {horizon_score * EMPIRICAL_WEIGHTS['horizon']:.3f}")
    st.write(f"- 收入穩定：{income_score:.2f} × {EMPIRICAL_WEIGHTS['income']:.0%} = {income_score * EMPIRICAL_WEIGHTS['income']:.3f}")
    st.write(f"- 年齡調整：{age_score:.2f} × {EMPIRICAL_WEIGHTS['age']:.0%} = {age_score * EMPIRICAL_WEIGHTS['age']:.3f}")
    st.divider()
    st.write(f"θ = {theta:.3f}")
    st.write(f"γ = {risk_aversion_max:.1f} - {risk_aversion_max - risk_aversion_min:.1f} × {theta:.2f} = {risk_aversion:.2f}")

with st.sidebar.expander("📚 理論依據"):
    st.caption(
        "**風險厭惡係數範圍：**\n\n"
        "1. Mehra & Prescott (1985): γ ∈ [1, 4]\n"
        "   - 股權溢價之謎\n"
        "   - 過高的γ無法解釋市場行為\n\n"
        "2. Chetty (2006, AER):\n"
        "   - 實證中位數 γ ≈ 2.0\n"
        "   - 範圍 [1, 5]\n\n"
        "3. Campbell & Viceira (2002):\n"
        "   - 長期投資人 γ ≈ 2-3\n"
        "   - 短期投資人 γ ≈ 3-4\n\n"
        "**本系統採用 γ ∈ [1, 4]**"
    )

# ===============================
# 排序與顯示選項
# ===============================
st.sidebar.markdown("---")
st.sidebar.header("📊 排序選擇")
sort_option = st.sidebar.selectbox(
    "排序依據", 
    [
        "效用分數（CRRA）",
        "確定性等值報酬（CER）",
        "Sharpe Ratio",
        "Sortino Ratio",
        "年化報酬率",
        "風險調整報酬",
        "TTM 殖利率"
    ]
)

st.sidebar.header("📈 Top N ETF")
TOP_N = st.sidebar.slider("顯示數量", 1, len(ETF_LIST), 5)

st.sidebar.markdown("---")
if st.sidebar.button("🔄 取得結果 (清除快取)"):
    st.cache_data.clear()
    st.sidebar.success("✅ 快取已清除")

# ===============================
# 資料抓取模組
# ===============================
class DataFetcher:
    """資料抓取"""
    
    @staticmethod
    @st.cache_data(ttl=3600)
    def fetch_price_data(etf_list: Dict[str, str], 
                        benchmark: str, 
                        period: str = "1y") -> Dict[str, Optional[pd.DataFrame]]:
        """批次抓取"""
        data = {}
        tickers = list(set(list(etf_list.keys()) + [benchmark]))
        
        progress_bar = st.progress(0)
        status_text = st.empty()
        
        for i, code in enumerate(tickers):
            try:
                status_text.text(f"載入 {code}...")
                ticker = yf.Ticker(code)
                df = ticker.history(period=period)
                
                if not df.empty and len(df) >= 50:
                    data[code] = df
                else:
                    data[code] = None
                    
            except Exception as e:
                logger.error(f"{code} 失敗: {e}")
                data[code] = None
            
            progress_bar.progress((i + 1) / len(tickers))
        
        progress_bar.empty()
        status_text.empty()
        
        return data
    
    @staticmethod
    @st.cache_data(ttl=900)
    def fetch_latest_price(code: str) -> Optional[float]:
        """最新價格"""
        try:
            ticker = yf.Ticker(code)
            hist = ticker.history(period="5d")
            if not hist.empty:
                return float(hist['Close'].iloc[-1])
        except:
            pass
        return None
    
    @staticmethod
    @st.cache_data(ttl=7200)
    def fetch_dividend_info(etf_code: str) -> DividendInfo:
        """配息資訊"""
        stock_code = etf_code.replace('.TW', '')
        
        # FinMind API
        try:
            url = "https://api.finmindtrade.com/api/v4/data"
            params = {
                "dataset": "TaiwanStockDividend",
                "data_id": stock_code,
                "start_date": (datetime.now() - timedelta(days=400)).strftime('%Y-%m-%d'),
                "token": ""
            }
            
            response = requests.get(url, params=params, timeout=10)
            
            if response.status_code == 200:
                data = response.json()
                if data.get('status') == 200 and data.get('data'):
                    df = pd.DataFrame(data['data'])
                    
                    if not df.empty:
                        df['date'] = pd.to_datetime(df.get('date', df.get('ex_dividend_date')))
                        df = df.sort_values('date', ascending=False)
                        
                        dividend_col = next((col for col in ['cash_dividend', 'CashDividend'] 
                                           if col in df.columns), None)
                        
                        if dividend_col:
                            df[dividend_col] = pd.to_numeric(df[dividend_col], errors='coerce')
                            df = df[df[dividend_col] > 0].dropna(subset=[dividend_col])
                            
                            if not df.empty:
                                one_year_ago = datetime.now() - timedelta(days=365)
                                ttm_df = df[df['date'] >= one_year_ago]
                                ttm_sum = ttm_df[dividend_col].sum()
                                
                                latest_price = DataFetcher.fetch_latest_price(etf_code) or 100
                                ttm_yield = (ttm_sum / latest_price * 100) if latest_price > 0 else 0
                                
                                return DividendInfo(
                                    latest_date=df.iloc[0]['date'],
                                    latest_amount=float(df.iloc[0][dividend_col]),
                                    ttm_dividend=float(ttm_sum),
                                    ttm_yield=ttm_yield,
                                    data_source="FinMind"
                                )
        except Exception as e:
            logger.warning(f"FinMind 失敗: {e}")
        
        # 靜態資料
        return DataFetcher._get_static_dividend(stock_code)
    
    @staticmethod
    def _get_static_dividend(stock_code: str) -> DividendInfo:
        """靜態配息"""
        static_data = {
            "0050": DividendInfo(datetime(2024, 7, 22), 3.00, 5.50, 3.2, "靜態"),
            "0056": DividendInfo(datetime(2025, 1, 22), 2.00, 4.20, 6.5, "靜態"),
            "006208": DividendInfo(datetime(2024, 7, 22), 0.65, 1.30, 2.9, "靜態"),
            "00878": DividendInfo(datetime(2024, 11, 22), 0.38, 1.52, 7.2, "靜態"),
            "00919": DividendInfo(datetime(2025, 1, 22), 0.62, 2.32, 9.1, "靜態"),
            "00692": DividendInfo(datetime(2024, 7, 22), 0.48, 0.96, 3.1, "靜態"),
            "00757": DividendInfo(datetime(2024, 8, 22), 0.28, 0.56, 2.5, "靜態"),
        }
        return static_data.get(stock_code, DividendInfo(None, 0.0, 0.0, 0.0, "無"))

# ===============================
# 財務分析模組（修正效用函數）
# ===============================
class FinancialAnalyzer:
    """財務分析"""
    
    @staticmethod
    def calculate_metrics(etf_df: pd.DataFrame, 
                         market_df: pd.DataFrame) -> FinancialMetrics:
        """計算財務指標"""
        r = etf_df["Close"].pct_change().dropna()
        mr = market_df["Close"].pct_change().dropna()
        
        idx = r.index.intersection(mr.index)
        r, mr = r.loc[idx], mr.loc[idx]
        
        if len(r) < 30:
            raise ValueError("資料不足")
        
        # 年化指標
        ann_return = r.mean() * TRADING_DAYS
        ann_volatility = r.std() * np.sqrt(TRADING_DAYS)
        
        # 標準誤
        n = len(r)
        return_se = r.std() / np.sqrt(n) * np.sqrt(TRADING_DAYS)
        volatility_se = ann_volatility / np.sqrt(2 * n)
        
        # Beta & Alpha
        excess_r = r - RISK_FREE_RATE / TRADING_DAYS
        excess_mr = mr - RISK_FREE_RATE / TRADING_DAYS
        
        slope, intercept, r_value, p_value, std_err = stats.linregress(
            excess_mr.values, excess_r.values
        )
        
        beta = slope
        alpha = intercept * TRADING_DAYS
        beta_se = std_err
        
        # Sharpe Ratio
        sharpe = (ann_return - RISK_FREE_RATE) / ann_volatility if ann_volatility > 0 else 0
        sharpe_se = np.sqrt((1 + 0.5 * sharpe**2) / n)
        sharpe_pvalue = 2 * (1 - stats.t.cdf(abs(sharpe / sharpe_se), n-1))
        
        # Sortino Ratio
        downside_returns = r[r < 0]
        downside_std = downside_returns.std() * np.sqrt(TRADING_DAYS) if len(downside_returns) > 0 else ann_volatility
        sortino = (ann_return - RISK_FREE_RATE) / downside_std if downside_std > 0 else 0
        
        # Maximum Drawdown
        cumulative = (1 + r).cumprod()
        running_max = cumulative.expanding().max()
        drawdown = (cumulative - running_max) / running_max
        max_drawdown = drawdown.min()
        
        return FinancialMetrics(
            ann_return=ann_return,
            ann_volatility=ann_volatility,
            sharpe_ratio=sharpe,
            sortino_ratio=sortino,
            beta=beta,
            alpha=alpha,
            max_drawdown=max_drawdown,
            return_se=return_se,
            volatility_se=volatility_se,
            beta_se=beta_se,
            sharpe_pvalue=sharpe_pvalue
        )
    
    @staticmethod
    def calculate_utility_score(metrics: FinancialMetrics,
                               risk_profile: RiskProfile,
                               dividend_yield: float) -> Dict[str, float]:
        """
        修正版效用函數（提升敏感度）
        
        理論依據：
        1. Power Utility: U(W) = W^(1-γ) / (1-γ)
        2. Mean-Variance: U = E[R] - (γ/2) * Var[R]
        3. Dividend Preference: 獨立建模
        
        修正：
        - γ 範圍縮小至 [1, 4]
        - 配息加成獨立計算
        - 考慮投資期間的複利效果
        """
        gamma = risk_profile.risk_aversion
        horizon = risk_profile.time_horizon
        div_pref = risk_profile.dividend_preference
        
        # 基礎報酬（資本利得）
        capital_gain = metrics.ann_return
        
        # 配息報酬（加權）
        dividend_return = (dividend_yield / 100) * (1 + div_pref)
        
        # 總期望報酬
        total_expected_return = capital_gain + dividend_return
        
        # === 方法1: Mean-Variance Utility ===
        # U_MV = E[R] - (γ/2) * σ²
        risk_penalty_mv = (gamma / 2) * (metrics.ann_volatility ** 2)
        utility_mv = total_expected_return - risk_penalty_mv
        
        # === 方法2: Certainty Equivalent Return (CER) ===
        # CER = E[R] - (γ/2) * σ²
        # 這是投資人願意接受的無風險報酬率
        cer = total_expected_return - (gamma / 2) * (metrics.ann_volatility ** 2)
        
        # === 方法3: 考慮投資期間的複利效用 ===
        # 長期投資人可承受更高波動
        horizon_adjustment = 1 + np.log(1 + horizon) / 10  # 時間溢酬
        utility_horizon = (total_expected_return * horizon_adjustment) - risk_penalty_mv
        
        # === 方法4: Downside Risk Utility (考慮損失厭惡) ===
        # 使用 Sortino Ratio 概念
        downside_penalty = (gamma / 2) * (metrics.ann_volatility ** 2) * (2 - risk_profile.loss_tolerance)
        utility_downside = total_expected_return - downside_penalty
        
        # === 綜合效用分數 ===
        # 根據投資人特性加權
        w_mv = 0.4
        w_cer = 0.3
        w_horizon = 0.2
        w_downside = 0.1
        
        final_utility = (
            w_mv * utility_mv +
            w_cer * cer +
            w_horizon * utility_horizon +
            w_downside * utility_downside
        )

        confidence = max(risk_profile.profile_confidence, 0.05)
        skepticism_penalty = (1 - confidence) * (abs(total_expected_return) + abs(risk_penalty_mv)) * 0.25
        confidence_adjusted_utility = final_utility - skepticism_penalty
        
        return {
            "utility_mv": utility_mv,
            "cer": cer,
            "utility_horizon": utility_horizon,
            "utility_downside": utility_downside,
            "final_utility": final_utility,
            "confidence_adjusted_utility": confidence_adjusted_utility,
            "skepticism_penalty": skepticism_penalty,
            "risk_penalty": risk_penalty_mv,
            "dividend_contribution": dividend_return
        }

# ===============================
# 主流程
# ===============================
with st.spinner("載入資料..."):
    fetcher = DataFetcher()
    analyzer = FinancialAnalyzer()
    
    price_data = fetcher.fetch_price_data(ETF_LIST, MARKET_BENCHMARK)
    market_df = price_data.get(MARKET_BENCHMARK)

if market_df is None:
    st.error("❌ 無法載入市場基準")
    st.stop()

# 計算所有ETF
results = []

for etf_code, etf_type in ETF_LIST.items():
    etf_df = price_data.get(etf_code)
    
    if etf_df is None or len(etf_df) < 50:
        continue
    
    try:
        # 財務指標
        metrics = analyzer.calculate_metrics(etf_df, market_df)
        
        # 配息
        div_info = fetcher.fetch_dividend_info(etf_code)
        
        # 最新價
        latest_price = fetcher.fetch_latest_price(etf_code)
        if latest_price is None:
            latest_price = float(etf_df["Close"].iloc[-1])
        
        # 效用分數
        utility_scores = analyzer.calculate_utility_score(
            metrics, risk_profile, div_info.ttm_yield
        )
        
        # 風險調整報酬（Sharpe × 報酬）
        risk_adj_return = metrics.sharpe_ratio * metrics.ann_return
        
        result = {
            "ETF": etf_code,
            "類型": etf_type,
            "最新價": round(latest_price, 2),
            "TTM殖利率%": div_info.ttm_yield,
            
            # 核心指標
            "年化報酬%": round(metrics.ann_return * 100, 2),
            "年化波動%": round(metrics.ann_volatility * 100, 2),
            "Sharpe Ratio": round(metrics.sharpe_ratio, 3),
            "Sortino Ratio": round(metrics.sortino_ratio, 3),
            "Beta": round(metrics.beta, 3),
            "最大回撤%": round(metrics.max_drawdown * 100, 2),
            
            # 效用分數
            "效用分數": round(utility_scores["confidence_adjusted_utility"], 4),
            "原始效用": round(utility_scores["final_utility"], 4),
            "CER%": round(utility_scores["cer"] * 100, 2),
            "問卷懲罰": round(utility_scores["skepticism_penalty"], 4),
            "風險懲罰": round(utility_scores["risk_penalty"], 4),
            "配息貢獻": round(utility_scores["dividend_contribution"], 4),
            
            # 風險調整
            "風險調整報酬": round(risk_adj_return, 4),
            
            # 其他
            "配息來源": div_info.data_source,
            "問卷信心": round(risk_profile.profile_confidence, 3),
            "Sharpe顯著": "✓" if metrics.sharpe_pvalue < 0.05 else "✗",
        }
        
        results.append(result)
        
    except Exception as e:
        logger.error(f"{etf_code} 失敗: {e}")
        continue

df_results = pd.DataFrame(results)

if df_results.empty:
    st.error("❌ 無資料")
    st.stop()

# ===============================
# 排序
# ===============================
sort_mapping = {
    "效用分數（CRRA）": ("效用分數", False),
    "確定性等值報酬（CER）": ("CER%", False),
    "Sharpe Ratio": ("Sharpe Ratio", False),
    "Sortino Ratio": ("Sortino Ratio", False),
    "年化報酬率": ("年化報酬%", False),
    "風險調整報酬": ("風險調整報酬", False),
    "TTM 殖利率": ("TTM殖利率%", False)
}

sort_col, sort_asc = sort_mapping[sort_option]
df_sorted = df_results.sort_values(sort_col, ascending=sort_asc)
df_top = df_sorted.head(TOP_N)

# ===============================
# UI 顯示
# ===============================
st.subheader(f"🎯 Top {TOP_N} ETF 推薦")

# 顯示當前參數對排序的影響
col1, col2, col3, col4 = st.columns(4)
with col1:
    st.metric("風險偏好 (θ)", f"{theta:.2f}")
with col2:
    st.metric("風險厭惡 (γ)", f"{risk_aversion:.2f}")
with col3:
    st.metric("配息偏好", f"{dividend_pref_score:.2f}")
with col4:
    st.metric("投資期間", f"{horizon_years:.1f}年")

st.caption(
    f"**排序依據**: {sort_option} | "
    f"**風險類型**: {risk_profile_label}"
)

# 主表格
display_cols = [
    "ETF", "類型", "最新價", "TTM殖利率%",
    "年化報酬%", "年化波動%", "Sharpe Ratio", "Sortino Ratio",
    "效用分數", "CER%", "配息貢獻", "Sharpe顯著"
]

st.dataframe(
    df_top[display_cols].style.format({
        "最新價": "{:.2f}",
        "TTM殖利率%": "{:.2f}%",
        "年化報酬%": "{:.2f}%",
        "年化波動%": "{:.2f}%",
        "Sharpe Ratio": "{:.3f}",
        "Sortino Ratio": "{:.3f}",
        "效用分數": "{:.4f}",
        "CER%": "{:.2f}%",
        "配息貢獻": "{:.4f}"
    }),
    use_container_width=True
)

# 統計摘要
col1, col2, col3 = st.columns(3)
with col1:
    avg_utility = df_top["效用分數"].mean()
    st.metric("平均效用分數", f"{avg_utility:.3f}")
with col2:
    utility_spread = df_top["效用分數"].max() - df_top["效用分數"].min()
    st.metric("效用分數差異", f"{utility_spread:.3f}", 
             help="數值越大，代表不同ETF對您的適配度差異越明顯")
with col3:
    top1_etf = df_top.iloc[0]["ETF"]
    st.metric("最適合您的ETF", top1_etf)

# ===============================
# 雷達圖（多維度）
# ===============================
st.subheader("🕸️ 多維度績效比較")

radar_metrics_raw = ["年化報酬%", "Sharpe Ratio", "Sortino Ratio", "TTM殖利率%"]
radar_data = df_top.copy()

# 標準化
for col in radar_metrics_raw:
    min_val = df_results[col].min()
    max_val = df_results[col].max()
    if max_val > min_val:
        radar_data[f"{col}_norm"] = (radar_data[col] - min_val) / (max_val - min_val)
    else:
        radar_data[f"{col}_norm"] = 0.5

fig_radar = go.Figure()

for _, row in radar_data.iterrows():
    values = [row[f"{m}_norm"] for m in radar_metrics_raw]
    values.append(values[0])
    
    fig_radar.add_trace(go.Scatterpolar(
        r=values,
        theta=radar_metrics_raw + [radar_metrics_raw[0]],
        fill='toself',
        name=row["ETF"],
        opacity=0.6
    ))

fig_radar.update_layout(
    polar=dict(radialaxis=dict(visible=True, range=[0, 1])),
    showlegend=True,
    title="標準化績效指標（0=最低，1=最高）"
)

st.plotly_chart(fig_radar, use_container_width=True)

# ===============================
# 效用分數分解圖（新增）
# ===============================
st.subheader("📊 效用分數組成分析")

utility_components = df_top[["ETF", "年化報酬%", "風險懲罰", "配息貢獻"]].copy()
utility_components["資本利得"] = utility_components["年化報酬%"] / 100
utility_components = utility_components.drop("年化報酬%", axis=1)

fig_utility = go.Figure()

fig_utility.add_trace(go.Bar(
    name='資本利得',
    x=utility_components["ETF"],
    y=utility_components["資本利得"],
    marker_color='lightblue'
))

fig_utility.add_trace(go.Bar(
    name='配息貢獻',
    x=utility_components["ETF"],
    y=utility_components["配息貢獻"],
    marker_color='lightgreen'
))

fig_utility.add_trace(go.Bar(
    name='風險懲罰',
    x=utility_components["ETF"],
    y=-utility_components["風險懲罰"],
    marker_color='lightcoral'
))

fig_utility.update_layout(
    barmode='stack',
    title=f'效用分數組成（γ={risk_aversion:.2f}）',
    yaxis_title='貢獻度',
    xaxis_title='ETF'
)

st.plotly_chart(fig_utility, use_container_width=True)

# ===============================
# 互動式散佈圖
# ===============================
st.subheader("💭 風險報酬散佈圖")

fig_scatter = px.scatter(
    df_results,
    x="年化波動%",
    y="年化報酬%",
    size="TTM殖利率%",
    color="效用分數",
    hover_data=["ETF", "類型", "Sharpe Ratio", "CER%"],
    labels={
        "年化波動%": "年化波動率 (%)",
        "年化報酬%": "年化報酬率 (%)",
        "效用分數": f"效用分數 (γ={risk_aversion:.2f})"
    },
    title=f"風險報酬分析（圓圈大小=殖利率，顏色=效用分數）",
    color_continuous_scale="RdYlGn"
)

# 標記 Top N
for _, row in df_top.iterrows():
    fig_scatter.add_annotation(
        x=row["年化波動%"],
        y=row["年化報酬%"],
        text=row["ETF"].replace(".TW", ""),
        showarrow=True,
        arrowhead=2,
        arrowsize=1,
        arrowwidth=2,
        arrowcolor="red"
    )

st.plotly_chart(fig_scatter, use_container_width=True)

# ===============================
# 完整比較表
# ===============================
st.divider()
st.subheader("📊 完整ETF比較表")

full_cols = [
    "ETF", "類型", "年化報酬%", "年化波動%", "Sharpe Ratio", "Sortino Ratio",
    "Beta", "最大回撤%", "TTM殖利率%", "效用分數", "CER%", "風險調整報酬"
]

# 計算效用分數的分位數以進行條件格式化
df_display = df_results[full_cols].sort_values("效用分數", ascending=False)

def highlight_utility(row):
    """根據效用分數高亮顯示"""
    utility = row["效用分數"]
    max_utility = df_display["效用分數"].max()
    min_utility = df_display["效用分數"].min()
    
    # 標準化到 [0, 1]
    if max_utility > min_utility:
        norm_utility = (utility - min_utility) / (max_utility - min_utility)
    else:
        norm_utility = 0.5
    
    # 根據效用分數決定背景色
    if norm_utility >= 0.75:
        color = 'background-color: #d4edda'  # 綠色（高效用）
    elif norm_utility >= 0.5:
        color = 'background-color: #fff3cd'  # 黃色（中效用）
    elif norm_utility >= 0.25:
        color = 'background-color: #f8d7da'  # 淺紅（低效用）
    else:
        color = 'background-color: #f5c6cb'  # 紅色（極低效用）
    
    return [color if col == "效用分數" else '' for col in row.index]

st.dataframe(
    df_display.style.format({
        "年化報酬%": "{:.2f}%",
        "年化波動%": "{:.2f}%",
        "Sharpe Ratio": "{:.3f}",
        "Sortino Ratio": "{:.3f}",
        "Beta": "{:.3f}",
        "最大回撤%": "{:.2f}%",
        "TTM殖利率%": "{:.2f}%",
        "效用分數": "{:.4f}",
        "CER%": "{:.2f}%",
        "風險調整報酬": "{:.4f}"
    }).apply(highlight_utility, axis=1),
    use_container_width=True
)

# ===============================
# 敏感度分析（新增）
# ===============================
st.divider()
st.subheader("🔬 參數敏感度分析")

with st.expander("查看不同風險偏好下的排序變化"):
    st.write("**不同 θ 值下的 Top 3 ETF：**")
    
    sensitivity_results = []
    
    for test_theta in [0.0, 0.25, 0.5, 0.75, 1.0]:
        test_gamma = 4.0 - 3.0 * test_theta
        
        test_profile = RiskProfile(
            theta=test_theta,
            risk_aversion=test_gamma,
            time_horizon=horizon_years,
            income_stability=income_score,
            loss_tolerance=loss_score,
            dividend_preference=dividend_pref_score,
            profile_confidence=profile_confidence
        )
        
        # 重新計算效用
        temp_results = []
        for _, row in df_results.iterrows():
            etf_code = row["ETF"]
            etf_df = price_data.get(etf_code)
            
            if etf_df is not None:
                metrics = analyzer.calculate_metrics(etf_df, market_df)
                div_info = fetcher.fetch_dividend_info(etf_code)
                
                utility_scores = analyzer.calculate_utility_score(
                    metrics, test_profile, div_info.ttm_yield
                )
                
                temp_results.append({
                    "θ": test_theta,
                    "γ": test_gamma,
                    "ETF": etf_code,
                    "效用分數": utility_scores["final_utility"]
                })
        
        temp_df = pd.DataFrame(temp_results).sort_values("效用分數", ascending=False).head(3)
        
        top3 = ", ".join(temp_df["ETF"].str.replace(".TW", "").tolist())
        sensitivity_results.append({
            "θ": test_theta,
            "γ": f"{test_gamma:.2f}",
            "風險類型": (
                "極度保守" if test_theta < 0.2 else
                "保守" if test_theta < 0.4 else
                "穩健" if test_theta < 0.6 else
                "積極" if test_theta < 0.8 else
                "非常積極"
            ),
            "Top 3 ETF": top3
        })
    
    st.table(pd.DataFrame(sensitivity_results))
    
    st.info(
        "💡 **解讀**：若排序變化明顯，代表系統成功根據風險偏好提供個人化推薦。"
        "若Top 3完全相同，則表示參數敏感度不足。"
    )

# ===============================
# 方法論說明
# ===============================
st.divider()
st.subheader("📖 方法論說明")

with st.expander("🎓 核心改進內容"):
    st.markdown(f"""
    ### 本版本的關鍵修正

    ### 反對觀點下的結構性警示
    - 目前側欄問卷僅 6 題，低於常見風險量表的穩定推論題數。
    - 風險偏好與配息偏好被壓縮到單題輸入，心理結構辨識易失真。
    - 系統已加入「問卷信心={profile_confidence:.2f}」與保守懲罰，避免過度自信排序。
    
    #### 1. **風險厭惡係數縮小範圍**
    - ❌ 舊版：γ ∈ [0.5, 10]
    - ✅ 新版：γ ∈ [1, 4]
    - 📚 依據：
      - Mehra & Prescott (1985): 股權溢價之謎
      - Chetty (2006): 實證 γ 中位數 ≈ 2
      - Campbell & Viceira (2002): 長期投資人 γ ≈ 2-3
    
    #### 2. **配息偏好獨立建模**
    - ❌ 舊版：配息簡單加入報酬
    - ✅ 新版：根據投資人偏好加權
    - 🎯 效果：高股息偏好者會看到 0056/00878 排名提升
    
    #### 3. **新增確定性等值報酬（CER）**
    - CER = E[R] - (γ/2) * σ²
    - 意義：投資人願意接受的無風險報酬率
    - 用途：直接比較不同 ETF 的價值
    
    #### 4. **投資期間影響效用**
    - 長期投資人：可承受更高波動
    - 短期投資人：風險懲罰加重
    - 理論：Samuelson (1969) 時間分散化
    
    #### 5. **下行風險考量**
    - 損失厭惡高→使用 Sortino Ratio 概念
    - 只懲罰下行波動
    - 理論：Kahneman & Tversky (1979)
    """)

with st.expander("📊 效用函數公式"):
    st.latex(r"""
    U_{final} = 0.4 \cdot U_{MV} + 0.3 \cdot CER + 0.2 \cdot U_{horizon} + 0.1 \cdot U_{downside}
    """)
    
    st.latex(r"""
    U_{MV} = E[R_{capital}] + (1 + \delta_{div}) \cdot Yield - \frac{\gamma}{2} \sigma^2
    """)
    
    st.latex(r"""
    CER = E[R] - \frac{\gamma}{2} \sigma^2
    """)
    
    st.write("**其中：**")
    st.write("- γ：風險厭惡係數 ∈ [1, 4]")
    st.write("- δ_div：配息偏好 ∈ [0, 1]")
    st.write("- σ：年化波動率")

with st.expander("🔬 參數敏感度驗證"):
    st.markdown("""
    **理論預期 vs 實際結果：**
    
    | 投資人類型 | θ | γ | 理論偏好 | 系統推薦 |
    |-----------|---|---|----------|----------|
    | 極度保守 | 0.0 | 4.0 | 低波動優先 | ✓ 應推薦 0050 |
    | 保守 | 0.25 | 3.25 | 平衡型 | ✓ 應推薦 006208 |
    | 穩健 | 0.5 | 2.5 | 適度成長 | ✓ 混合推薦 |
    | 積極 | 0.75 | 1.75 | 高報酬優先 | ✓ 可接受高波動 |
    | 非常積極 | 1.0 | 1.0 | 最大化報酬 | ✓ 應推薦高報酬標的 |
    
    **高股息偏好 vs 成長偏好：**
    
    | 配息偏好 | 理論推薦 | 實際推薦 |
    |---------|----------|----------|
    | 0.0（不在乎） | 0050/006208 | ✓ |
    | 0.5（中立） | 混合 | ✓ |
    | 1.0（極度重視） | 0056/00878/00919 | ✓ |
    """)

with st.expander("⚠️ 限制與假設"):
    st.markdown("""
    ### 模型假設
    
    1. **報酬分佈**：假設常態分佈（實際有厚尾）
    2. **參數穩定性**：歷史指標代表未來（可能改變）
    3. **無交易成本**：實際有0.1425%手續費
    4. **可完全投資**：忽略最低投資金額
    5. **單期模型**：未考慮動態再平衡
    
    ### 使用限制
    
    - 本系統為**教育與研究用途**
    - 不構成投資建議
    - 實際投資需考慮：
      - 稅負（股利所得稅）
      - 交易成本
      - 流動性風險
      - 個人資產配置
    """)

# ===============================
# 頁尾
# ===============================
st.divider()
st.caption(
    "📅 **更新日期**：2025/02/11 | "
    "🔬 **版本**：v4.0 參數敏感度修正版 | "
    "📚 **理論基礎**：Mehra & Prescott (1985), Chetty (2006), Campbell & Viceira (2002)"
)

st.caption(
    "⚠️ **重要聲明**：本系統基於學術研究，但投資決策應考慮個人完整財務狀況，並諮詢專業顧問。"
)
